######################################################################
# Automatically generated by qmake (3.0) Sun May 19 11:49:28 2013
######################################################################

TEMPLATE = app
TARGET = tests
INCLUDEPATH += .
QT += testlib
# Input
HEADERS += ../gitproject/gitproject.h
SOURCES += testgitproject.cpp ../gitproject/gitproject.cpp
